site_name: wrf_to_int
site_description: Utility to convert wrf output to WPS intermediate files

repo_url: https://github.com/wrf_to_int
repo_name: mullenkamp/wrf_to_int

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: red
          accent: indigo
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: red
          accent: indigo
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [.]
                import:
                    - https://docs.python.org/3.10/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - wrf_to_int

nav:
    - About: index.md
    - Reference:
        - wrf_to_int: reference/wrf_to_int.md
